### ISSUE TITLE
Preliminary API work to load in first 3 parks and expedite future additions to MVD

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/reserve-rec-api#23]
#### Description:

We need to start building out the API so we can load in the data that is being collected for MVD. With the MVD in various stages of completeness, it is pragmatic to build out some rudimentary endpoints so that as the data comes in, it can be quickly added to/updated in the database the same way, every time, and we don't have to perform manual migrations directly do the database. 

With the Data Model in its infancy, it is important to factor in the possibility the data model may change as we collect more data, but for now we can start with the model outlined in [#3](https://github.com/bcgov/reserve-rec-api/issues/3) and the data reviewed from https://github.com/bcgov/reserve-rec-public/issues/22

Similar to CMS, we should start with Protected Areas as being the background for all data, since most items that will be contained in the database can be traced back to some parent Protected Area.

#### Acceptance Criteria:

- [ ] Construct a preliminary API with endpoints to leverage as data is collected 

#### Development Checklist:

- [x] Build nightly cron to sync protected area data from Data Register (we can use this as a protected area source of truth for now).
- [x] Investigate areas where we will need to pull data from other sources nightly.
- [x] Create OPTIONS, GET, PUT, POST, and DELETE endpoints for the various datatypes in the data model as necessary (not every datatype will need every endpoint) .
- [x] Use the created endpoints to populate the DEV database.
- [x] Amalgamate multiple sources into single datatypes wherever possible (combine citywide/CMS/etc). Document which fields come from which sources in these situations

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by cameronpettit** [comment]
What has been done for this ticket so far:

Because we have access to the Name Data Register, which is the source of truth for name data for all protected areas, we can sync with the Register to get a list of all protected areas that should be in our system. A [nightly cron](https://github.com/bcgov/reserve-rec-api/tree/main/handlers/synchronization/syncDataRegister) has been set up to perform this sync.

We've also added a [sync for CMS protected area data](https://github.com/bcgov/reserve-rec-api/tree/main/handlers/synchronization/syncCMSProtectedAreas) contained in Strapi. In Strapi, the protected area is the 'backbone' that links most of the data contained in Strapi - so establishing a sync is a stepping stone to pulling data from CMS in the future. The only datapoint that the sync is set up to pull in currently is the geospatial centroid of the park. There is no nightly cron set up yet as the sync is expensive.

Finally, we've added a [sync for Tantalis protected area geospatial data](https://github.com/bcgov/reserve-rec-api/tree/main/handlers/synchronization/syncTantalisProtectedAreas). This sync fetches geospatial boundary data for protected areas from Tantalis (the recognized source of truth). This query is also expensive so this lambda is only deployable manually - we don't really expect park boundaries to change very often. The geoJSON returned by this query is so large that sometimes it exceeds the allowable limit for data rows in DynamoDB, so this sync directly inserts the geoJSON into OpenSearch. We are unable to query DynamoDB for geospatial data anyways.

OpenSearch Dashboards can now be used to view centroids, boundaries, and other metadata for all protected areas.

Following the [data model](https://github.com/bcgov/reserve-rec-api/blob/main/docs/data-model/dataModel-2024-07-19.md) outlined in #3, data has been collected for 3 trial protected areas:

- Strathcona (orcs 1)
- Cape Scott (orcs 250)
- Juan de Fuca (orcs 9398)

For these 3 trial areas, the database has been populated with places policies, permits, and inventory corresponding to the experiences offered at these areas. 

There are only 3 'experiences' offered within this set: Backcountry registration. Each park has a permit in the database for this experience.

```
pk: permit::<orcs>
sk: backcountryRegistration::1
```

The following endpoints have been created to simplify certain data operations:
### Protected Areas:
```
GET: /protected-areas
PUT: /protected-areas
GET: /protected-areas/{orcs}
PUT: /protected-areas/{orcs}
```
### Policies
```
GET: /policies/{policyType}
POST: /policies/{policyType}
PUT: /policies/{policyType}
GET: /policies/{policyType}/{policyId}
```
### Non-protected area Places (Cam zones)
```
GET: /places/{orcs}
GET: /places/{orcs}/{placeType}
GET: /places/{orcs}/{placeType}/{placeId}
```
### Permits
```
GET: /permits/{orcs}
GET: /permits/{orcs}/{permitType}
GET: /permits/{orcs}/{permitType}/{permitId}
```
### Inventory
```
GET: /inventory/{orcs}/{placeType/{placeId}
GET: /inventory/{orcs}/{placeType/{placeId}/{inventoryType}
GET: /inventory/{orcs}/{placeType/{placeId}/{inventoryType}/{inventoryId}
```

Finally, a [Postman library](https://github.com/bcgov/reserve-rec-api/tree/main/docs/postman) has been created to assist developers in exploring the above endpoints. You will need to load in the collection and the environments provided in the repo. To get the authorization to work within Postman, you will need to go into each environment and update the `cognito_client_id` to the client id found in Cognito in the respective AWS environment. Then go to 'Authorization' in the root folder of the collection and hit 'Get New Access Token'.

This first iteration of the database is merely a jumping off point so please raise any and all concerns as the purpose of getting this iteration out ASAP is to spur on discussions over what works and what doesn't as early as possible.

**Comment by LindsayMacfarlane** [comment]
Amazing! Thank you @cameronpettit. Double checking if there is anything specific I can/should be testing out as part of PO review for this ticket.

**Comment by cameronpettit** [comment]
@LindsayMacfarlane If you don't already have access to our DynamoDB and OpenSearch consoles, I would get established there so you know how to access our data straight from the source. Other than that I don't think theres anything else.

**Comment by LindsayMacfarlane** [comment]
Going to approve/close this ticket as we work out my access to DynamoDB and OpenSearch. Thanks for getting me sorted out @cameronpettit !
