### ISSUE TITLE
PRDT: Data Modelling

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-api#3]
#### Description:

Create a data model for Reservations...................................
https://github.com/bcgov/reserve-rec-api/issues/6

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]
- [ ] 

#### Development Checklist:

- [ ] modelling in aws - no sql workbench 
- [ ] Documentation for other devs to understand what schemas are, primary keys, etc. eventually, accessible to anyone (aws standpoint)
- [ ] ...

#### Dependencies

- Blocked by
- Blocking #1 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
New goal since we don't have all the data:
- "we think this is the data that is available - here's a schema that's going along with that projection"

**Comment by Dianadec** [comment]
@cameronpettit  is working on this already alongside #6

**Comment by cameronpettit** [comment]
Data model jumping off point documented [here](https://github.com/bcgov/reserve-rec-api/blob/main/docs/data-model/dataModel-2024-07-19.md). Does not include how we will be handling geospatial data. Intended to be worked on iteratively but we need to wait until scope is solidified a bit more. Several teams appear to be working on data modeling activities simultaneously. Will revisit when scope is clearer, but for a starting point, we will need the datapoints outlined in this markdown doc and we can set about locating the sources of truth for these datapoints.

**Comment by meyerdarcie** [comment]
Moving this ticket to done as we are moving forward with proposed data model for backcountry MVP - FYI @cameronpettit
