### ISSUE TITLE
Explore how to connect with the DAM

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/reserve-rec-api#31]
#### Description:

It may be possible to pull images directly from the DAM (aka resourcespace) through an API. Let's figure out how we can do that!

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]

#### Development Checklist:

- [x] Reach out to Rob/Rex to see what is possible
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Ask DAM team:
- is there an API
- is there documentation about how to use it

If not available, it is not ready for devs to use.
Last convo, they were not ready for people to consume the data via api.

**Comment by Dianadec** [comment]
Moved to blocked since I believe we are waiting to have a conversation with someone? @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Meeting notes with Rex.

- There is an API available (documentation: -	https://www.resourcespace.com/knowledge-base/api/) 
- Rob is confident that the API is good, but wants to research it a bit more
- Rob and team are currently investigating whether they can host the DAM internally on AWS or if they will use the vendors AWS platform. There are technical as well as PIA/STRA considerations that will influence the teams direction.
- If Info Services moves with the internally hosted option, estimated timeline is to do the migration in January.
- Current leanings is towards internally hosted, but TBD
- Next steps is for Rob to fully deploy the DAM on internal AWS, they would then tag or create an album specifically for our use
- Note: specific campground sites pictures are not yet in the DAM

Next steps for us:

- reconnect with Rex late January for an update
- determine as a team on best approach - live copy, webhook, scheduled cronjob?
- Determine how many pictures we want and what type

cc @Dianadec

**Comment by LindsayMacfarlane** [comment]
Sent meeting invite for late Jan to reconnect with Rex on where things are at/status update.
