### ISSUE TITLE
Onboarding for BCeID and BCSC

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-api#34]
#### Description:

Meet with IDIM team for official BCeID/BCSC kickoff. 

#### Development Checklist:

- [x] Send out email/note to folks to let them know the purpose of the kickoff session
- [x] Have session with IDIM team
- [x] Identify next steps

#### Dependencies

- Blocked by 
- Blocking #32 and #33 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
Various next steps will be needed as part of this process, including:
- PIA
- STRA
- Communication strategy
- and the actual development work!

New tickets will be created or existing ones updated to reflect this.
