### ISSUE TITLE
PRDT: Determine Vanity URL

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-api#4]
#### Description:

Determine whether this vanity URL will work (get team input). Darcie & Jess agree with it.

https://reserve.bcparks.ca/dayuse/
https://reserve.bcparks.ca/backcountry/

**Relevant documentation as reference**

**Comment by Dianadec** [comment]
@JLWade 's idea: 

https://reserve.bcparks.ca/dayuse/
https://reserve.bcparks.ca/backcountry/

cc @meyerdarcie

**Comment by meyerdarcie** [comment]
Fantastic - we should go with this unless there is strong rationale otherwise.

**Comment by Dianadec** [comment]
Question - is this ticket also needing to be about certificates...? (just referencing the comment from this ticket: https://github.com/bcgov/reserve-rec-api/issues/5)

**Comment by Dianadec** [comment]
Refinement notes: Will keep this as-is, then we will need to change it down the road, at which point we will setup a redirect.
