### ISSUE TITLE
[L] PRDT: Implement first iteration of mapping tool front-end

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-api#8]
#### Description:

After #7 

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]

#### Development Checklist:

- [ ] Mapbox UI (https://docs.mapbox.com/#maps)
- [ ] Shape data pulled from a search endpoint and points/polygons rendered (See API ticket #7 )
- [ ] Popup designs can be implemented in parallel

#### Dependencies

- Blocked 
- Blocking
- Related to #2 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by marklise** [comment]
@Dianadec @meredithom there's some UI needing to be spun up for popups in the map

**Comment by Dianadec** [comment]
@meredithom  want the design broken into a sep ticket?

**Comment by meyerdarcie** [comment]
Refinement notes Aug 6:
- need more understanding of rationale for mapbox @marklise
- what compliance/budget would we need to complete in advance of implementation
- Would 3D layers be supported by gov? Could be connections/useful for RST @JLWade
